pipeline:
  build:
    image: plugins/docker
    repo: registry.honestbee.com/swagger-ui
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    branches: [ master ]

  deploy:
    image: quay.io/honestbee/drone-helm
    skip_tls_verify: true
    reuse_values: true
    helm_repos: hb-charts=http://helm-charts.honestbee.com
    chart: hb-charts/swagger-ui
    values: image.repository=registry.honestbee.com/honestbee/swagger-ui,image.tag=${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    release: swagger-ui-master
    prefix: PROD
    when:
      branch: [ master ]

  notify:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: feed-devops
    when:
      status: [ success, failure ]
